export enum BOOKING_STATUS {
  PENDING = 'PENDING',
  QUOTED = 'QUOTED',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum JOB_STATUS {
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  STARTED = 'STARTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum PAYMENT_STATUS {
  CREATED = 'CREATED',
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PAYMENT_TYPE {
  ADVANCE = 'ADVANCE',
  FINAL = 'FINAL',
  FULL = 'FULL',
}

export enum PAYMENT_PROVIDER {
  RAZORPAY = 'RAZORPAY',
  STRIPE = 'STRIPE',
  CASH = 'CASH',
}

export enum ASSIGNMENT_TYPE {
  AUTO_MATCHED = 'AUTO_MATCHED',
  MANUALLY_ASSIGNED = 'MANUALLY_ASSIGNED',
}

export enum FOLLOWUP_OUTCOME {
  CONNECTED = 'CONNECTED',
  NO_ANSWER = 'NO_ANSWER',
  CALLBACK_REQUESTED = 'CALLBACK_REQUESTED',
  RESOLVED = 'RESOLVED',
}

export enum FOLLOWUP_RELATED_TO {
  CUSTOMER = 'CUSTOMER',
  PARTNER = 'PARTNER',
}

export enum ESCALATION_SEVERITY {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ESCALATION_STATUS {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum ESCALATION_RAISED_BY {
  CUSTOMER = 'CUSTOMER',
  PARTNER = 'PARTNER',
  SYSTEM = 'SYSTEM',
}
